export const GET_FIREBASE_DATA = "GET_FIREBASE_DATA";
export const GET_JOB_DATA = "GET_JOB_DATA";
export const GET_APPLIED_JOBS = "GET_APPLIED_JOBS";
export const GET_APPLIED_STUDENT_DATA = "GET_APPLIED_STUDENT_DATA";
